name: 🐛 Bug report
description: Report something that is not working as expected
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        Please provide as much detail as possible so we can reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide a minimal example or steps to reproduce the issue.
      placeholder: |
        1. Run ...
        2. Call ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / error messages
      description: Paste any relevant logs or stack traces.
      render: shell
